# install my favorite plugins
apm install atom-beautify
apm install code-peek
apm install color-picker
apm install double-tag
apm install emmet
apm install highlight-selected
apm install last-cursor-position
apm install linter
apm install linter-erb
apm install linter-jshint
apm install linter-rubocop
apm install minimap
apm install pigments
apm install rails-snippets
apm install rspec-snippets
apm install sort-lines
apm install linter-shellcheck
apm install linter-javac
